project:
  type: website
  output-dir: docs

website:
  title: "CLINTA PUTHUSSERY VARGHESE"
  description:
    Course Projects for STA 9750 at Baruch College
   site-url:https://clintavarghese.github.io/STA9750-2024-FALL/index.html
   repo-url:https://github.com/clintavarghese/STA9750-2024-FALL
   repo-actions:[edit, source, issue]
  navbar:
    background: primary
    search: true
    
format:
  html:
    theme:
        - darkly
    toc: false